# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# Expose the port that Flask will run on (optional for tests)
# EXPOSE 5000

# Define environment variable(s) for testing
ENV DATABASE_URL_TEST=postgresql://postgres:postgres@db_test:5432/test_database
ENV FLASK_ENV=testing

# Command to run the tests
CMD ["pytest", "test/test_app.py"]
